// Sample data for initial development and demo purposes
// This will be replaced by live API data from the data pipeline

import { StateSummary, DashboardAlert, ExecutiveInsight, SignalItem, RiskOpportunityItem, TexasPulseMetric } from "./types";

export const sampleStateSummaries: StateSummary[] = [
  {
    stateCode: "TX",
    stateName: "Texas",
    enrollment: 5_842_000,
    enrollmentChange: -8.2,
    perEnrolleeSpending: 7_450,
    managedCarePenetration: 92,
    qualityScore: 62,
    expansionStatus: "not_expanded",
  },
  {
    stateCode: "CA",
    stateName: "California",
    enrollment: 14_267_000,
    enrollmentChange: -6.1,
    perEnrolleeSpending: 9_830,
    managedCarePenetration: 82,
    qualityScore: 71,
    expansionStatus: "expanded",
  },
  {
    stateCode: "FL",
    stateName: "Florida",
    enrollment: 5_183_000,
    enrollmentChange: -11.3,
    perEnrolleeSpending: 6_920,
    managedCarePenetration: 88,
    qualityScore: 58,
    expansionStatus: "not_expanded",
  },
  {
    stateCode: "NY",
    stateName: "New York",
    enrollment: 7_892_000,
    enrollmentChange: -4.7,
    perEnrolleeSpending: 12_150,
    managedCarePenetration: 78,
    qualityScore: 74,
    expansionStatus: "expanded",
  },
  {
    stateCode: "OH",
    stateName: "Ohio",
    enrollment: 3_156_000,
    enrollmentChange: -5.8,
    perEnrolleeSpending: 8_670,
    managedCarePenetration: 90,
    qualityScore: 67,
    expansionStatus: "expanded",
  },
  {
    stateCode: "GA",
    stateName: "Georgia",
    enrollment: 2_487_000,
    enrollmentChange: -9.4,
    perEnrolleeSpending: 6_380,
    managedCarePenetration: 85,
    qualityScore: 55,
    expansionStatus: "partial",
  },
  {
    stateCode: "IL",
    stateName: "Illinois",
    enrollment: 3_621_000,
    enrollmentChange: -5.2,
    perEnrolleeSpending: 8_140,
    managedCarePenetration: 76,
    qualityScore: 68,
    expansionStatus: "expanded",
  },
  {
    stateCode: "PA",
    stateName: "Pennsylvania",
    enrollment: 3_489_000,
    enrollmentChange: -6.9,
    perEnrolleeSpending: 9_280,
    managedCarePenetration: 84,
    qualityScore: 70,
    expansionStatus: "expanded",
  },
  {
    stateCode: "LA",
    stateName: "Louisiana",
    enrollment: 1_823_000,
    enrollmentChange: -7.1,
    perEnrolleeSpending: 7_890,
    managedCarePenetration: 91,
    qualityScore: 59,
    expansionStatus: "expanded",
  },
  {
    stateCode: "MS",
    stateName: "Mississippi",
    enrollment: 782_000,
    enrollmentChange: -6.5,
    perEnrolleeSpending: 7_120,
    managedCarePenetration: 83,
    qualityScore: 48,
    expansionStatus: "not_expanded",
  },
  {
    stateCode: "TN",
    stateName: "Tennessee",
    enrollment: 1_692_000,
    enrollmentChange: -8.8,
    perEnrolleeSpending: 7_340,
    managedCarePenetration: 100,
    qualityScore: 61,
    expansionStatus: "not_expanded",
  },
  {
    stateCode: "OK",
    stateName: "Oklahoma",
    enrollment: 1_234_000,
    enrollmentChange: -4.3,
    perEnrolleeSpending: 7_560,
    managedCarePenetration: 79,
    qualityScore: 56,
    expansionStatus: "expanded",
  },
];

export const sampleEnrollmentTrends: Record<string, { month: string; value: number }[]> = {
  TX: [
    { month: "2025-01", value: 6_350_000 },
    { month: "2025-02", value: 6_280_000 },
    { month: "2025-03", value: 6_210_000 },
    { month: "2025-04", value: 6_150_000 },
    { month: "2025-05", value: 6_090_000 },
    { month: "2025-06", value: 6_040_000 },
    { month: "2025-07", value: 5_990_000 },
    { month: "2025-08", value: 5_950_000 },
    { month: "2025-09", value: 5_920_000 },
    { month: "2025-10", value: 5_890_000 },
    { month: "2025-11", value: 5_865_000 },
    { month: "2025-12", value: 5_842_000 },
  ],
  CA: [
    { month: "2025-01", value: 15_200_000 },
    { month: "2025-02", value: 15_080_000 },
    { month: "2025-03", value: 14_960_000 },
    { month: "2025-04", value: 14_850_000 },
    { month: "2025-05", value: 14_740_000 },
    { month: "2025-06", value: 14_650_000 },
    { month: "2025-07", value: 14_560_000 },
    { month: "2025-08", value: 14_480_000 },
    { month: "2025-09", value: 14_410_000 },
    { month: "2025-10", value: 14_350_000 },
    { month: "2025-11", value: 14_305_000 },
    { month: "2025-12", value: 14_267_000 },
  ],
  FL: [
    { month: "2025-01", value: 5_840_000 },
    { month: "2025-02", value: 5_760_000 },
    { month: "2025-03", value: 5_680_000 },
    { month: "2025-04", value: 5_610_000 },
    { month: "2025-05", value: 5_540_000 },
    { month: "2025-06", value: 5_470_000 },
    { month: "2025-07", value: 5_410_000 },
    { month: "2025-08", value: 5_360_000 },
    { month: "2025-09", value: 5_310_000 },
    { month: "2025-10", value: 5_260_000 },
    { month: "2025-11", value: 5_220_000 },
    { month: "2025-12", value: 5_183_000 },
  ],
  NY: [
    { month: "2025-01", value: 8_280_000 },
    { month: "2025-02", value: 8_230_000 },
    { month: "2025-03", value: 8_180_000 },
    { month: "2025-04", value: 8_130_000 },
    { month: "2025-05", value: 8_080_000 },
    { month: "2025-06", value: 8_040_000 },
    { month: "2025-07", value: 8_000_000 },
    { month: "2025-08", value: 7_970_000 },
    { month: "2025-09", value: 7_940_000 },
    { month: "2025-10", value: 7_920_000 },
    { month: "2025-11", value: 7_905_000 },
    { month: "2025-12", value: 7_892_000 },
  ],
};

export const sampleAlerts: DashboardAlert[] = [
  {
    id: "1",
    stateCode: "FL",
    stateName: "Florida",
    type: "enrollment_change",
    severity: "high",
    title: "Florida enrollment dropped 11.3% YoY",
    description:
      "Florida's Medicaid enrollment decline is the steepest among large states, likely driven by aggressive redetermination processes post-unwinding.",
    date: "2025-12-15",
    metric: "enrollment",
    change: -11.3,
    sourceUrl: "https://www.kff.org/medicaid/issue-brief/medicaid-enrollment-and-unwinding-tracker/",
    sourceLabel: "KFF Medicaid Unwinding Tracker",
  },
  {
    id: "2",
    stateCode: "TX",
    stateName: "Texas",
    type: "policy_change",
    severity: "medium",
    title: "Federal work requirements take effect Jan 2027",
    description:
      "The 2025 Reconciliation Act's work requirements may affect partial expansion planning and legislative discussions. While Texas hasn't expanded, this may shape legislative posture.",
    date: "2025-12-08",
    sourceUrl: "https://www.congress.gov/",
    sourceLabel: "Congress.gov — 2025 Reconciliation Act",
  },
  {
    id: "3",
    stateCode: "NY",
    stateName: "New York",
    type: "spending_spike",
    severity: "medium",
    title: "NY per-enrollee spending up 9.2%",
    description:
      "New York's per-enrollee costs continue to rise faster than the national average, driven by pharmacy and behavioral health spending.",
    date: "2025-11-30",
    metric: "perEnrolleeSpending",
    change: 9.2,
    sourceUrl: "https://www.medicaid.gov/medicaid/financial-management/state-expenditure-reporting/expenditure-reports/index.html",
    sourceLabel: "CMS MBES Expenditure Reports",
  },
  {
    id: "4",
    stateCode: "GA",
    stateName: "Georgia",
    type: "policy_change",
    severity: "high",
    title: "Georgia partial expansion under review",
    description:
      "Georgia's Pathways to Coverage 1115 waiver (partial expansion with work requirements) faces federal review under the new reconciliation framework.",
    date: "2025-12-20",
    sourceUrl: "https://www.medicaid.gov/medicaid/section-1115-demonstrations/index.html",
    sourceLabel: "CMS 1115 Demonstration Waivers",
  },
  {
    id: "5",
    stateCode: "MS",
    stateName: "Mississippi",
    type: "quality_alert",
    severity: "high",
    title: "Mississippi quality score lowest in nation",
    description:
      "Mississippi's composite quality score of 48 ranks last among all states, with particular weakness in maternal health and preventive care metrics.",
    date: "2025-12-01",
    metric: "qualityScore",
    sourceUrl: "https://www.medicaid.gov/medicaid/quality-of-care/performance-measurement/adult-and-child-health-care-quality-measures/index.html",
    sourceLabel: "CMS Core Set Quality Measures",
  },
];

export const sampleSpendingCategories = [
  { category: "Managed Care", amount: 26_800, percentOfTotal: 61.5 },
  { category: "Fee-for-Service", amount: 5_200, percentOfTotal: 11.9 },
  { category: "Prescription Drugs", amount: 4_100, percentOfTotal: 9.4 },
  { category: "Long-Term Care", amount: 3_800, percentOfTotal: 8.7 },
  { category: "Behavioral Health", amount: 2_100, percentOfTotal: 4.8 },
  { category: "Admin & Other", amount: 1_600, percentOfTotal: 3.7 },
];

// --- Executive Attention Now: AI-ranked insight cards ---
export const sampleInsights: ExecutiveInsight[] = [
  {
    id: "ei-1",
    rank: 1,
    title: "HHSC Procurement Forecast Signals Adjacent Opportunity",
    summary: "The Q3 2026 HHSC procurement forecast includes a new data analytics modernization RFP scoped at $45-60M, directly adjacent to current TMHP BusOps capabilities.",
    whyItMatters: "This is the first major HHSC analytics procurement since the modular transition. Accenture's BusOps incumbency and data access create a structural advantage if positioned early.",
    confidence: "high",
    category: "competitive",
    impactLevel: "critical",
    actionPrompt: "Brief growth team on adjacency; request pre-RFP engagement with HHSC analytics lead",
    relatedStates: ["TX"],
    source: "HHSC Procurement Forecast",
    sourceUrl: "https://www.txsmartbuy.com/sp",
    timestamp: "2026-04-07",
  },
  {
    id: "ei-2",
    rank: 2,
    title: "Texas Enrollment Decline Accelerating Beyond Peer Median",
    summary: "Texas enrollment declined 8.2% YoY vs. the non-expansion peer median of 6.8%. The gap widened 1.4 points in the last quarter, driven by redetermination pacing.",
    whyItMatters: "Faster-than-peer enrollment declines may trigger HHSC scrutiny of call center capacity and outreach effectiveness, both within BusOps scope. Also affects managed-care capitation revenue projections.",
    confidence: "high",
    category: "operational",
    impactLevel: "high",
    actionPrompt: "Review outreach metrics with BusOps ops lead; prepare proactive HHSC talking points",
    relatedStates: ["TX", "FL", "TN"],
    source: "CMS Enrollment Snapshot + Pipeline Analysis",
    sourceUrl: "https://www.medicaid.gov/medicaid/program-information/medicaid-and-chip-enrollment-data/index.html",
    timestamp: "2026-04-06",
  },
  {
    id: "ei-3",
    rank: 3,
    title: "CMS All-State Call: New FMAP Methodology Takes Effect Oct 2026",
    summary: "CMS confirmed the revised FMAP calculation methodology in the March all-state call. Texas FMAP may shift 1.2-1.8 points, affecting state budget allocation for FY2027.",
    whyItMatters: "FMAP changes directly affect the state/federal cost split. If state share increases, HHSC will face budget pressure that could accelerate scope negotiations and amendment activity on all major contracts.",
    confidence: "medium",
    category: "regulatory",
    impactLevel: "high",
    actionPrompt: "Model FMAP impact scenarios; align finance team on amendment strategy",
    relatedStates: ["TX"],
    source: "CMS All-State Call Materials",
    sourceUrl: "https://www.medicaid.gov/federal-policy-guidance/index.html",
    timestamp: "2026-04-03",
  },
  {
    id: "ei-4",
    rank: 4,
    title: "Quality Score Gap Closing But Still Below 65th Percentile",
    summary: "Texas quality composite improved 2 points to 62, but remains in the 38th percentile nationally. Behavioral health and maternal health metrics are the biggest drags.",
    whyItMatters: "Quality scores increasingly factor into CMS waiver approvals and public reporting. A score below the 50th percentile creates risk if Texas pursues any 1115 waiver modifications.",
    confidence: "high",
    category: "quality",
    impactLevel: "moderate",
    actionPrompt: "Map quality improvement levers within BusOps scope; prepare for quality review prep",
    relatedStates: ["TX"],
    source: "CMS Core Set + Pipeline Analysis",
    sourceUrl: "https://www.medicaid.gov/medicaid/quality-of-care/performance-measurement/adult-and-child-health-care-quality-measures/index.html",
    timestamp: "2026-04-05",
  },
];

// --- Signals from the Edge ---
export const sampleSignals: SignalItem[] = [
  {
    id: "sig-1",
    title: "HHSC posts RFI for Medicaid data lake modernization",
    summary: "HHSC released a Request for Information seeking vendor capabilities in cloud-based Medicaid data integration and analytics, with responses due May 15.",
    source: "HHSC Procurement",
    category: "procurement",
    relevance: "high",
    timestamp: "2026-04-05",
    affectedStates: ["TX"],
  },
  {
    id: "sig-2",
    title: "CMS issues guidance on Medicaid unwinding data reporting",
    summary: "New CMS guidance requires states to submit monthly ex parte renewal rates and procedural disenrollment counts starting July 2026.",
    source: "CMS Policy",
    category: "cms",
    relevance: "high",
    timestamp: "2026-04-03",
  },
  {
    id: "sig-3",
    title: "Texas OIG quarterly report: focus on managed care encounter data",
    summary: "The OIG's Q1 2026 report flags incomplete encounter data submissions from two Texas MCOs, recommending enhanced data validation protocols.",
    source: "Texas OIG",
    category: "oig",
    relevance: "high",
    timestamp: "2026-04-01",
    affectedStates: ["TX"],
  },
  {
    id: "sig-4",
    title: "Ohio Medicaid MMIS modernization RFP released",
    summary: "Ohio released its next-generation MMIS procurement with a $200M ceiling. Timeline targets vendor selection by Q4 2026.",
    source: "Ohio Procurement",
    category: "procurement",
    relevance: "medium",
    timestamp: "2026-03-28",
    affectedStates: ["OH"],
  },
  {
    id: "sig-5",
    title: "TMHP notice: claims processing system maintenance window extended",
    summary: "TMHP notified providers of an extended maintenance window for the claims adjudication system, April 12-14, due to infrastructure upgrades.",
    source: "TMHP Notice",
    category: "regulatory",
    relevance: "medium",
    timestamp: "2026-04-02",
    affectedStates: ["TX"],
  },
  {
    id: "sig-6",
    title: "Senate Finance Committee schedules Medicaid block grant hearing",
    summary: "The Senate Finance Committee announced a May 2026 hearing on Medicaid per-capita cap proposals, with CBO scoring expected by mid-April.",
    source: "Congressional",
    category: "legislative",
    relevance: "medium",
    timestamp: "2026-03-30",
  },
  {
    id: "sig-7",
    title: "North Carolina begins Medicaid managed care transition",
    summary: "NC launched Phase 2 of its Medicaid managed care transition, shifting behavioral health populations to managed care as of April 1.",
    source: "NC DHHS",
    category: "policy",
    relevance: "low",
    timestamp: "2026-03-25",
    affectedStates: ["NC"],
  },
];

// --- Risk & Opportunity Matrix ---
export const sampleRiskOpportunity: RiskOpportunityItem[] = [
  {
    id: "ro-1",
    label: "HHSC Data Analytics RFP",
    description: "Adjacent $45-60M procurement for Medicaid data modernization",
    risk: 20,
    opportunity: 88,
    impact: 85,
    trend: "improving",
    category: "procurement",
    sourceUrl: "https://www.txsmartbuy.com/sp",
    recommendedAction: "Brief growth team; request pre-RFP engagement with HHSC analytics lead",
  },
  {
    id: "ro-2",
    label: "Enrollment Decline Scrutiny",
    description: "HHSC attention on redetermination outreach effectiveness",
    risk: 72,
    opportunity: 25,
    impact: 70,
    trend: "deteriorating",
    category: "operations",
    sourceUrl: "https://www.kff.org/medicaid/issue-brief/medicaid-enrollment-and-unwinding-tracker/",
    recommendedAction: "Review outreach metrics with BusOps ops lead; prepare proactive HHSC briefing",
  },
  {
    id: "ro-3",
    label: "FMAP Methodology Change",
    description: "Revised federal cost-sharing calculation effective Oct 2026",
    risk: 65,
    opportunity: 35,
    impact: 80,
    trend: "stable",
    category: "policy",
    sourceUrl: "https://www.medicaid.gov/medicaid/financial-management/federal-matching-assistance-percentages/index.html",
    recommendedAction: "Model FMAP scenarios for FY2027 budget; align with finance lead",
  },
  {
    id: "ro-4",
    label: "Ohio MMIS Pursuit",
    description: "Next-gen MMIS procurement in Ohio, $200M ceiling",
    risk: 35,
    opportunity: 75,
    impact: 90,
    trend: "improving",
    category: "competitive",
    sourceUrl: "https://procure.ohio.gov/",
    recommendedAction: "Confirm pursuit decision; stand up Ohio capture team by end of quarter",
  },
  {
    id: "ro-5",
    label: "Quality Score Trajectory",
    description: "Texas quality composite improving but below 50th percentile",
    risk: 50,
    opportunity: 45,
    impact: 55,
    trend: "improving",
    category: "quality",
    sourceUrl: "https://www.medicaid.gov/medicaid/quality-of-care/performance-measurement/adult-and-child-health-care-quality-measures/index.html",
    recommendedAction: "Map quality improvement levers within BusOps scope",
  },
  {
    id: "ro-6",
    label: "OIG Encounter Data Focus",
    description: "OIG flagging managed care encounter data completeness",
    risk: 60,
    opportunity: 30,
    impact: 50,
    trend: "deteriorating",
    category: "operations",
    sourceUrl: "https://oig.hhs.gov/reports/",
    recommendedAction: "Audit encounter data pipeline completeness; prep remediation memo",
  },
  {
    id: "ro-7",
    label: "EVV Contract Extension",
    description: "Electronic Visit Verification contract renewal window approaching",
    risk: 30,
    opportunity: 60,
    impact: 65,
    trend: "stable",
    category: "procurement",
    sourceUrl: "https://www.medicaid.gov/medicaid/home-community-based-services/guidance/electronic-visit-verification-evv/index.html",
    recommendedAction: "Submit extension request 60 days before renewal window opens",
  },
  {
    id: "ro-8",
    label: "Federal Block Grant Risk",
    description: "Senate hearing on Medicaid per-capita caps could reshape state budgets",
    risk: 75,
    opportunity: 15,
    impact: 95,
    trend: "deteriorating",
    category: "policy",
    sourceUrl: "https://www.congress.gov/",
    recommendedAction: "Monitor legislation; brief leadership on per-capita cap exposure",
  },
];

// --- Texas Pulse ribbon metrics ---
export const samplePulseMetrics: TexasPulseMetric[] = [
  {
    label: "Enrollment",
    value: "5.84M",
    delta: "-8.2% YoY",
    deltaDirection: "down",
    tooltip: "Total Texas Medicaid & CHIP members as of the most recent CMS monthly snapshot. Year-over-year change reflects net enrollment movement across all eligibility categories.",
    sourceUrl: "https://www.medicaid.gov/medicaid/program-information/medicaid-and-chip-enrollment-data/index.html",
  },
  {
    label: "12-Mo Delta",
    value: "-508K",
    delta: "vs -420K peers",
    deltaDirection: "down",
    tooltip: "Net change in Texas enrollment over the trailing twelve months. Peer benchmark is the median of non-expansion states over the same period.",
    sourceUrl: "https://www.medicaid.gov/medicaid/program-information/medicaid-and-chip-enrollment-data/index.html",
  },
  {
    label: "Per Enrollee",
    value: "$7,450",
    delta: "+4.2% YoY",
    deltaDirection: "up",
    tooltip: "Average annual Medicaid spending per Texas enrollee, drawn from CMS MBES/CBES (CMS-64) reports. Rising costs can signal care intensity shifts, pharmacy pressure, or utilization changes.",
    sourceUrl: "https://www.medicaid.gov/medicaid/financial-management/state-expenditure-reporting/expenditure-reports/index.html",
  },
  {
    label: "Managed Care",
    value: "92%",
    deltaDirection: "neutral",
    tooltip: "Share of Texas Medicaid enrollees served through managed care organizations (STAR, STAR+PLUS, STAR Kids, STAR Health). Texas has one of the highest managed care penetration rates in the country.",
    sourceUrl: "https://www.medicaid.gov/medicaid/managed-care/enrollment/index.html",
  },
  {
    label: "Quality Score",
    value: "62/100",
    delta: "+2 pts",
    deltaDirection: "up",
    tooltip: "Composite quality score derived from CMS Adult & Child Core Set measures. Includes preventive care, chronic disease management, behavioral health, and maternal health. Texas currently sits in the 38th percentile nationally.",
    sourceUrl: "https://www.medicaid.gov/medicaid/quality-of-care/performance-measurement/adult-and-child-health-care-quality-measures/index.html",
  },
  {
    label: "Procurement Items",
    value: "3 active",
    delta: "1 new this week",
    deltaDirection: "neutral",
    tooltip: "Count of open or imminent HHSC Medicaid-related procurements being tracked on the Texas SmartBuy forecast and solicitation board. Used as a leading indicator of upcoming competitive activity.",
    sourceUrl: "https://www.txsmartbuy.com/sp",
  },
  {
    label: "OIG Signals",
    value: "2 open",
    delta: "encounter data focus",
    deltaDirection: "neutral",
    tooltip: "Active HHS Office of Inspector General reports, memos, or investigations touching Texas Medicaid operations. Current focus areas drive audit and remediation priorities.",
    sourceUrl: "https://oig.hhs.gov/reports/",
  },
  {
    label: "Next Major Milestone",
    value: "47 days",
    delta: "EVV renewal window",
    deltaDirection: "neutral",
    tooltip: "Days remaining until the next scheduled HHSC contract, waiver, or policy milestone requiring Accenture action. Used to pace leadership attention and capture team readiness.",
    sourceUrl: "https://www.medicaid.gov/medicaid/home-community-based-services/guidance/electronic-visit-verification-evv/index.html",
  },
];
