"use client";

import { useState, useEffect, useCallback } from "react";
import { StateSummary, DashboardAlert } from "./types";
import {
  sampleStateSummaries,
  sampleEnrollmentTrends,
  sampleAlerts,
} from "./sample-data";
import { US_STATES } from "./constants";

export interface IntelligenceData {
  executiveSummary: string;
  texasSpotlight: string;
  source: "claude_api" | "template" | null;
}

export interface DashboardData {
  states: StateSummary[];
  trends: Record<string, { month: string; value: number }[]>;
  alerts: DashboardAlert[];
  intelligence: IntelligenceData | null;
  dataSource: "pipeline" | "sample";
  lastUpdated: string;
  isLoading: boolean;
}

/**
 * Safely fetch JSON from a URL, returning null on failure.
 */
async function fetchJson<T>(url: string): Promise<T | null> {
  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    return await resp.json();
  } catch {
    return null;
  }
}

/**
 * Hook that tries to load live pipeline data from all agents,
 * and falls back to sample data for any missing pieces.
 *
 * Pipeline files (generated by Python agents into public/data/):
 * - enrollment.json  → enrollment counts & trends
 * - expenditure.json → spending data & per-enrollee costs
 * - quality.json     → Core Set quality scores
 * - intelligence.json → AI briefings & anomaly alerts
 */
export function useDashboardData(): DashboardData {
  const [data, setData] = useState<DashboardData>({
    states: sampleStateSummaries,
    trends: sampleEnrollmentTrends,
    alerts: sampleAlerts,
    intelligence: null,
    dataSource: "sample",
    lastUpdated: new Date().toISOString(),
    isLoading: true,
  });

  const loadPipelineData = useCallback(async () => {
    // Fetch all pipeline outputs in parallel
    const [enrollment, expenditure, quality, intelligence] = await Promise.all([
      fetchJson<{
        states: Array<{
          stateCode: string;
          stateName: string;
          enrollment: number;
          enrollmentChange: number | null;
        }>;
        trends: Record<string, { month: string; value: number }[]>;
        updated: string;
      }>("/data/enrollment.json"),
      fetchJson<{
        states: Array<{
          stateCode: string;
          totalExpenditures: number;
          perEnrolleeSpending: number | null;
          spendingChange: number | null;
        }>;
      }>("/data/expenditure.json"),
      fetchJson<{
        states: Array<{
          stateCode: string;
          qualityScore: number;
          qualityTier: string;
        }>;
      }>("/data/quality.json"),
      fetchJson<{
        executiveSummary: string;
        texasSpotlight: string;
        alerts: Array<{
          title: string;
          severity: string;
          description: string;
          states: string[];
          category: string;
          timestamp: string;
        }>;
        source: string;
      }>("/data/intelligence.json"),
    ]);

    const hasPipelineData = enrollment?.states && enrollment.states.length > 0;

    if (!hasPipelineData) {
      // No pipeline data at all — use sample data
      setData((prev) => ({
        ...prev,
        dataSource: "sample",
        isLoading: false,
      }));
      return;
    }

    // Build expenditure and quality lookup maps
    const expenditureByState: Record<string, { perEnrolleeSpending: number; spendingChange: number | null }> = {};
    if (expenditure?.states) {
      for (const s of expenditure.states) {
        expenditureByState[s.stateCode] = {
          perEnrolleeSpending: s.perEnrolleeSpending ?? 0,
          spendingChange: s.spendingChange,
        };
      }
    }

    const qualityByState: Record<string, number> = {};
    if (quality?.states) {
      for (const s of quality.states) {
        qualityByState[s.stateCode] = s.qualityScore;
      }
    }

    // Merge all pipeline data into unified state summaries
    const mergedStates: StateSummary[] = enrollment!.states.map((ps) => {
      const sample = sampleStateSummaries.find((s) => s.stateCode === ps.stateCode);
      const stateInfo = US_STATES[ps.stateCode];
      const expData = expenditureByState[ps.stateCode];
      const qualScore = qualityByState[ps.stateCode];

      return {
        stateCode: ps.stateCode,
        stateName: ps.stateName || stateInfo?.name || ps.stateCode,
        enrollment: ps.enrollment,
        enrollmentChange: ps.enrollmentChange ?? sample?.enrollmentChange ?? 0,
        perEnrolleeSpending: expData?.perEnrolleeSpending ?? sample?.perEnrolleeSpending ?? 0,
        managedCarePenetration: sample?.managedCarePenetration ?? 0, // Not yet from pipeline
        qualityScore: qualScore ?? sample?.qualityScore ?? 0,
        expansionStatus:
          (stateInfo?.expansionStatus as StateSummary["expansionStatus"]) ?? "not_expanded",
      };
    });

    // Merge alerts: prefer intelligence agent alerts, fall back to sample
    let mergedAlerts: DashboardAlert[] = sampleAlerts;
    if (intelligence?.alerts && intelligence.alerts.length > 0) {
      mergedAlerts = intelligence.alerts.map((a) => ({
        id: `ai-${a.title.replace(/\s+/g, "-").toLowerCase().slice(0, 30)}`,
        stateCode: (a.states && a.states[0]) || "US",
        stateName: (a.states && a.states[0]) || "National",
        type: "policy_change" as DashboardAlert["type"],
        title: a.title,
        severity: a.severity as DashboardAlert["severity"],
        description: a.description,
        date: a.timestamp || new Date().toISOString().split("T")[0],
      }));
    }

    // Intelligence briefings
    const intelligenceData: IntelligenceData | null = intelligence
      ? {
          executiveSummary: intelligence.executiveSummary,
          texasSpotlight: intelligence.texasSpotlight,
          source: intelligence.source as IntelligenceData["source"],
        }
      : null;

    setData({
      states: mergedStates.length > 0 ? mergedStates : sampleStateSummaries,
      trends:
        enrollment!.trends && Object.keys(enrollment!.trends).length > 0
          ? enrollment!.trends
          : sampleEnrollmentTrends,
      alerts: mergedAlerts,
      intelligence: intelligenceData,
      dataSource: "pipeline",
      lastUpdated: enrollment!.updated || new Date().toISOString(),
      isLoading: false,
    });
  }, []);

  useEffect(() => {
    loadPipelineData();
  }, [loadPipelineData]);

  return data;
}
