"use client";

import { useState, useEffect, useCallback } from "react";
import {
  StateSummary,
  DashboardAlert,
  ExecutiveInsight,
  SignalItem,
  RiskOpportunityItem,
  TexasPulseMetric,
} from "./types";
import {
  sampleStateSummaries,
  sampleEnrollmentTrends,
  sampleAlerts,
  sampleInsights,
  sampleSignals,
  sampleRiskOpportunity,
  samplePulseMetrics,
  sampleSpendingCategories,
} from "./sample-data";
import { US_STATES } from "./constants";

export interface IntelligenceData {
  executiveSummary: string;
  texasSpotlight: string;
  source: "claude_api" | "template" | null;
}

export interface SpendingCategory {
  category: string;
  amount: number;
  percentOfTotal: number;
}

export interface DashboardData {
  states: StateSummary[];
  trends: Record<string, { month: string; value: number }[]>;
  alerts: DashboardAlert[];
  intelligence: IntelligenceData | null;
  executiveInsights: ExecutiveInsight[];
  signals: SignalItem[];
  riskOpportunity: RiskOpportunityItem[];
  pulseMetrics: TexasPulseMetric[];
  spendingCategories: SpendingCategory[];
  dataSource: "pipeline" | "sample";
  lastUpdated: string;
  isLoading: boolean;
}

/**
 * Safely fetch JSON from a URL, returning null on failure.
 */
async function fetchJson<T>(url: string): Promise<T | null> {
  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    return await resp.json();
  } catch {
    return null;
  }
}

interface EnrollmentJson {
  states: Array<{
    stateCode: string;
    stateName: string;
    enrollment: number;
    enrollmentChange: number | null;
  }>;
  trends: Record<string, { month: string; value: number }[]>;
  updated: string;
}

interface ExpenditureJson {
  states: Array<{
    stateCode: string;
    totalExpenditures: number;
    perEnrolleeSpending: number | null;
    spendingChange: number | null;
    rollupBreakdown?: Record<string, number>;
  }>;
  national?: {
    rollupBreakdown?: Record<string, number>;
    rollupBreakdownPct?: Record<string, number>;
  };
}

interface QualityJson {
  states: Array<{
    stateCode: string;
    qualityScore: number;
    qualityTier: string;
    qualityScoreChange: number | null;
  }>;
}

interface ManagedCareJson {
  states: Array<{
    stateCode: string;
    managedCarePenetration: number | null;
    managedCareEnrollment: number;
    penetrationChange?: number | null;
  }>;
}

interface SignalsJson {
  signals: SignalItem[];
}

interface IntelligenceJson {
  executiveSummary: string;
  texasSpotlight: string;
  alerts: Array<{
    title: string;
    severity: string;
    description: string;
    states?: string[];
    category?: string;
    timestamp?: string;
    sourceLabel?: string;
    sourceUrl?: string;
  }>;
  executiveInsights?: ExecutiveInsight[];
  riskOpportunity?: RiskOpportunityItem[];
  pulseMetrics?: TexasPulseMetric[];
  source: string;
}

/**
 * Hook that tries to load live pipeline data from all agents,
 * and falls back to sample data for any missing pieces.
 *
 * Pipeline files (generated by Python agents into public/data/):
 * - enrollment.json    → enrollment counts & trends
 * - expenditure.json   → spending data, per-enrollee costs, rollup breakdown
 * - quality.json       → Core Set quality scores + YoY change
 * - managed_care.json  → managed care penetration per state
 * - signals.json       → external signals from Federal Register, OIG, Congress, procurement
 * - intelligence.json  → AI briefings, executive insights, risk/opportunity, pulse metrics
 */
export function useDashboardData(): DashboardData {
  const [data, setData] = useState<DashboardData>({
    states: sampleStateSummaries,
    trends: sampleEnrollmentTrends,
    alerts: sampleAlerts,
    intelligence: null,
    executiveInsights: sampleInsights,
    signals: sampleSignals,
    riskOpportunity: sampleRiskOpportunity,
    pulseMetrics: samplePulseMetrics,
    spendingCategories: sampleSpendingCategories as SpendingCategory[],
    dataSource: "sample",
    lastUpdated: new Date().toISOString(),
    isLoading: true,
  });

  const loadPipelineData = useCallback(async () => {
    // Fetch all pipeline outputs in parallel
    const [
      enrollment,
      expenditure,
      quality,
      managedCare,
      signals,
      intelligence,
    ] = await Promise.all([
      fetchJson<EnrollmentJson>("/data/enrollment.json"),
      fetchJson<ExpenditureJson>("/data/expenditure.json"),
      fetchJson<QualityJson>("/data/quality.json"),
      fetchJson<ManagedCareJson>("/data/managed_care.json"),
      fetchJson<SignalsJson>("/data/signals.json"),
      fetchJson<IntelligenceJson>("/data/intelligence.json"),
    ]);

    const hasPipelineData = enrollment?.states && enrollment.states.length > 0;

    if (!hasPipelineData) {
      // No pipeline data at all — use sample data
      setData((prev) => ({
        ...prev,
        dataSource: "sample",
        isLoading: false,
      }));
      return;
    }

    // Build lookup maps
    const expenditureByState: Record<
      string,
      { perEnrolleeSpending: number; spendingChange: number | null }
    > = {};
    if (expenditure?.states) {
      for (const s of expenditure.states) {
        expenditureByState[s.stateCode] = {
          perEnrolleeSpending: s.perEnrolleeSpending ?? 0,
          spendingChange: s.spendingChange,
        };
      }
    }

    const qualityByState: Record<
      string,
      { score: number; change: number | null }
    > = {};
    if (quality?.states) {
      for (const s of quality.states) {
        qualityByState[s.stateCode] = {
          score: s.qualityScore,
          change: s.qualityScoreChange,
        };
      }
    }

    const managedCareByState: Record<string, { penetration: number | null; change: number | null }> = {};
    if (managedCare?.states) {
      for (const s of managedCare.states) {
        managedCareByState[s.stateCode] = {
          penetration: s.managedCarePenetration,
          change: s.penetrationChange ?? null,
        };
      }
    }

    // Merge all pipeline data into unified state summaries
    const mergedStates: StateSummary[] = enrollment!.states.map((ps) => {
      const sample = sampleStateSummaries.find(
        (s) => s.stateCode === ps.stateCode
      );
      const stateInfo = US_STATES[ps.stateCode];
      const expData = expenditureByState[ps.stateCode];
      const qual = qualityByState[ps.stateCode];
      const mcData = managedCareByState[ps.stateCode];

      return {
        stateCode: ps.stateCode,
        stateName: ps.stateName || stateInfo?.name || ps.stateCode,
        enrollment: ps.enrollment,
        enrollmentChange:
          ps.enrollmentChange ?? sample?.enrollmentChange ?? 0,
        perEnrolleeSpending:
          expData?.perEnrolleeSpending ?? sample?.perEnrolleeSpending ?? 0,
        perEnrolleeSpendingChange: expData?.spendingChange ?? null,
        managedCarePenetration:
          mcData?.penetration ?? sample?.managedCarePenetration ?? 0,
        managedCarePenetrationChange: mcData?.change ?? null,
        qualityScore: qual?.score ?? sample?.qualityScore ?? 0,
        qualityScoreChange: qual?.change ?? null,
        expansionStatus:
          (stateInfo?.expansionStatus as StateSummary["expansionStatus"]) ??
          "not_expanded",
      } as StateSummary;
    });

    // Merge alerts: prefer intelligence agent alerts, fall back to sample
    let mergedAlerts: DashboardAlert[] = sampleAlerts;
    if (intelligence?.alerts && intelligence.alerts.length > 0) {
      mergedAlerts = intelligence.alerts.map((a, idx) => ({
        id: `ai-${idx}-${a.title.replace(/\s+/g, "-").toLowerCase().slice(0, 30)}`,
        stateCode: (a.states && a.states[0]) || "US",
        stateName: (a.states && a.states[0]) || "National",
        type: "policy_change" as DashboardAlert["type"],
        title: a.title,
        severity: a.severity as DashboardAlert["severity"],
        description: a.description,
        date: (a.timestamp || new Date().toISOString()).split("T")[0],
        sourceLabel: a.sourceLabel,
        sourceUrl: a.sourceUrl,
      }));
    }

    // Intelligence briefings
    const intelligenceData: IntelligenceData | null = intelligence
      ? {
          executiveSummary: intelligence.executiveSummary,
          texasSpotlight: intelligence.texasSpotlight,
          source: intelligence.source as IntelligenceData["source"],
        }
      : null;

    // Executive insights, risk/opportunity, pulse metrics
    const executiveInsights =
      intelligence?.executiveInsights && intelligence.executiveInsights.length > 0
        ? intelligence.executiveInsights
        : sampleInsights;

    const riskOpportunity =
      intelligence?.riskOpportunity && intelligence.riskOpportunity.length > 0
        ? intelligence.riskOpportunity
        : sampleRiskOpportunity;

    const pulseMetrics =
      intelligence?.pulseMetrics && intelligence.pulseMetrics.length > 0
        ? intelligence.pulseMetrics
        : samplePulseMetrics;

    // Signals feed — deduplicate by title (keep first / most recent)
    const rawSignals =
      signals?.signals && signals.signals.length > 0
        ? signals.signals
        : sampleSignals;
    const seenTitles = new Set<string>();
    const liveSignals = rawSignals.filter((s) => {
      if (seenTitles.has(s.title)) return false;
      seenTitles.add(s.title);
      return true;
    });

    // Spending categories (6 buckets) from expenditure national rollup
    let spendingCategories: SpendingCategory[] =
      sampleSpendingCategories as SpendingCategory[];
    if (expenditure?.national?.rollupBreakdown) {
      const rollup = expenditure.national.rollupBreakdown;
      const pct = expenditure.national.rollupBreakdownPct || {};
      const nationalEnrollment = (expenditure.states || []).reduce(
        (sum: number, s: { enrollment?: number | null }) =>
          sum + (s.enrollment || 0),
        0
      );
      spendingCategories = Object.entries(rollup).map(([category, amount]) => ({
        category,
        amount:
          nationalEnrollment > 0
            ? Math.round((amount as number) / nationalEnrollment)
            : (amount as number),
        percentOfTotal: pct[category] ?? 0,
      }));
    }

    setData({
      states:
        mergedStates.length > 0 ? mergedStates : sampleStateSummaries,
      trends:
        enrollment!.trends && Object.keys(enrollment!.trends).length > 0
          ? enrollment!.trends
          : sampleEnrollmentTrends,
      alerts: mergedAlerts,
      intelligence: intelligenceData,
      executiveInsights,
      signals: liveSignals,
      riskOpportunity,
      pulseMetrics,
      spendingCategories,
      dataSource: "pipeline",
      lastUpdated: enrollment!.updated || new Date().toISOString(),
      isLoading: false,
    });
  }, []);

  useEffect(() => {
    loadPipelineData();
  }, [loadPipelineData]);

  return data;
}
